# GENERAL
set -g prefix C-a
bind C-a send-prefix
bind r source-file ~/.tmux.conf

source-file ~/.config/tmux/gruvbox

# better splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ',*256col*:Tc'

# BAR
set-option -g status on
set-option -g status-bg $BG
set-option -g status-fg $FG

## COLORS
stack_bg=$BLUE
stack_fg=$BG
stack1_bg=$BLUE1

set -g base-index 1
set-option -g status-left "#[bg=$stack_bg,fg=$stack_fg] working on #[bold]#S #[bg=$stack_fg,fg=$stack_bg]"
set-option -g status-left-length 140

set-option -g status-right "#[bg=$stack_fg,fg=$stack1_bg]#[bg=$stack1_bg,fg=$stack_fg]   %H:%M #[bg=$stack1_bg,fg=$stack_bg]#[bg=$stack_bg,fg=$stack_fg]   %d-%B-%y "
set-option -g status-right-length 140

set-window-option -g window-status-current-format '[ #W]'
set-window-option -g window-status-format '#I:#W'
set-option -g status-justify centre

# Last session
bind -r P switch-client -l
unbind ?
bind -r ? neww "tmux-cht"
bind -r N neww "~/scripts/muix"
bind -r H run-shell "muix karu"

# MOVES BETWEEN PANES
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-p' select-pane -l


# Copy mode
setw -g mode-keys vi
set-option -s set-clipboard off
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-a

