#!/bin/bash

# Obtener los apoiments de hoy
# calcurse --input-datefmt 2 -g --filter-start-from today --filter-end-before tomorrow

TODAY_DAY=$(date +%d/%m/%Y)
TODAY_HOUR=$(date +%R)

CURRENT_APOIMENT=$(calcurse --input-datefmt 2 -G --filter-start-before "$TODAY_DAY $TODAY_HOUR" --filter-end-from "$TODAY_DAY $TODAY_HOUR" --filter-type apt)
echo $CURRENT_APOIMENT | awk -F '|' '{print $2}'
