#!/bin/bash

GRIVE=/usr/bin/grive
LOCAL_PATH=/repositorio/Drive
TIMEOUT=300

while true
do
    inotifywait -t $TIMEOUT -e modify -e move -e create -e delete -r $LOCAL_PATH
    cd $LOCAL_PATH &&  pwd && $GRIVE

done

