#!/bin/bash
PDF_FOLDER=$HOME/Phd/Database/Papers/
FILE=$(ls $PDF_FOLDER | rofi -theme-str "#window { width: 900;}" -dmenu -sort -sorting-method fzf -i -p "Choose to open")

OPEN=$PDF_FOLDER$FILE

if [[ $FILE != "" ]]; then
	notify-send -t 3000 "Opening pdf" "$FILE"
	okular "$OPEN"
else
	notify-send -t 3000 "Not filed selected"
fi

