#!/bin/bash

# Mutea y desmutea según su estado
[ $(pamixer --get-mute) = true ]&&
    pactl set-sink-mute 0 toggle 

# Disminuye el volumen
pactl set-sink-volume 0 -5%

# Actualiza el bloque
# pkill -RTMIN+10 dwmblocks
